<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Bootrom\A2\bootrom-combined.bin" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Bootrom\A2\bootrom-combined.bin" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />

    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
